- name: Listen to Events
  hosts: localhost
  sources:
  - name: Listen to the Host and Port
    ansible.eda.webhook:
      host: 0.0.0.0
      port: 5001
  filters:
    - ansible.eda.insert_hosts_to_meta:
        host_path: "payload.host"
  rules:
    - name: Rules to process the web
      condition: event.payload is defined
      action:
        run_job_template:
          name: Remove Package
          organization: Default
          job_args:
            extra_vars:
              package: "{{ event.payload.package.name }}"
