- name: Remove Package
  hosts: all
  become: true
  tasks:
    - name: Remove Package {{ package }}
      ansible.builtin.package:
        name: "{{ package }}"
        state: absent
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
